// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXil6VaHvoWioy745F7tuFBbjRTHz2VwQ',
    appId: '1:781239493924:web:d885b85505bbcfa65f3fb1',
    messagingSenderId: '781239493924',
    projectId: 'booksearch-4314b',
    authDomain: 'booksearch-4314b.firebaseapp.com',
    storageBucket: 'booksearch-4314b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxdGNuzsucPVa8UH_FnH8coH3Q7F5sTgg',
    appId: '1:781239493924:android:f862ca77da135c2c5f3fb1',
    messagingSenderId: '781239493924',
    projectId: 'booksearch-4314b',
    storageBucket: 'booksearch-4314b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmHZxF9HEtRTTlZFuBzJPSyqWizojLCY',
    appId: '1:781239493924:ios:c98dbca5a98e550f5f3fb1',
    messagingSenderId: '781239493924',
    projectId: 'booksearch-4314b',
    storageBucket: 'booksearch-4314b.appspot.com',
    iosClientId: '781239493924-8168bdt3invccc86fbhebq7iges0qb38.apps.googleusercontent.com',
    iosBundleId: 'com.example.booksearch',
  );
}
